import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Provider from "@/components/Context/provider";
import React, { Suspense } from "react";
import "./globals.css";
import  config  from "@/config";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const data = await fetch(`${config.host}/api/getData`);
  let res = await data.json();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><React.Suspense fallback={<div><h1>进入页面的加载项。。。</h1></div>}>
          <Provider datas={res}>
            <AntdRegistry>
              <Header></Header>
              {children}
            </AntdRegistry>
          </Provider>
        </React.Suspense>
      </body>
    </html>
  );
}